import { getDatabase } from './db';

export type CoinImageHashRow = {
  coin_id: string;
  side: 'obverse' | 'reverse';
  hash: string;
};

const BUNDLED_HASHES_VERSION = '1';

export function upsertCoinImageHashes(rows: CoinImageHashRow[]) {
  const db = getDatabase();
  for (const row of rows) {
    db.runSync(
      `INSERT OR REPLACE INTO coin_image_hashes (coin_id, side, hash) VALUES (?, ?, ?)`,
      row.coin_id,
      row.side,
      row.hash,
    );
  }
}

export function getAllCoinImageHashes(): CoinImageHashRow[] {
  const db = getDatabase();
  return db.getAllSync<CoinImageHashRow>('SELECT coin_id, side, hash FROM coin_image_hashes');
}

export function countCoinImageHashes(): number {
  const db = getDatabase();
  const row = db.getFirstSync<{ n: number }>('SELECT COUNT(*) AS n FROM coin_image_hashes');
  return row?.n ?? 0;
}

/** Load precomputed hashes shipped with the app (generated by `npm run catalog:hashes`). */
export function ensureBundledCatalogHashesLoaded(): void {
  const db = getDatabase();
  const current = db.getFirstSync<{ value: string }>(
    "SELECT value FROM meta WHERE key = 'catalog_hashes_version'",
  );
  if (current?.value === BUNDLED_HASHES_VERSION && countCoinImageHashes() > 0) return;

  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const bundle = require('@/assets/catalog/coin-image-hashes.json') as {
      version: string;
      entries: CoinImageHashRow[];
    };
    if (bundle.version !== BUNDLED_HASHES_VERSION || !bundle.entries?.length) return;
    db.execSync('DELETE FROM coin_image_hashes');
    upsertCoinImageHashes(bundle.entries);
    db.runSync(
      `INSERT OR REPLACE INTO meta (key, value) VALUES ('catalog_hashes_version', ?)`,
      BUNDLED_HASHES_VERSION,
    );
  } catch (e) {
    console.warn('[CoinFlip] catalog image hashes bundle missing — run npm run catalog:hashes', e);
  }
}
